import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        display: ["var(--font-sans)", "Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        canvas: "hsl(var(--canvas))",
        "surface-soft": "hsl(var(--surface-soft))",
        "surface-card": "hsl(var(--surface-card))",
        "surface-strong": "hsl(var(--surface-strong))",
        "surface-dark": "hsl(var(--surface-dark))",
        "surface-dark-elevated": "hsl(var(--surface-dark-elevated))",
        ink: "hsl(var(--ink))",
        "body-strong": "hsl(var(--body-strong))",
        body: "hsl(var(--body))",
        muted: "hsl(var(--muted))",
        "muted-soft": "hsl(var(--muted-soft))",
        hairline: "hsl(var(--hairline))",
        "on-dark": "hsl(var(--on-dark))",
        "brand-pink": "hsl(var(--brand-pink))",
        "brand-teal": "hsl(var(--brand-teal))",
        "brand-lavender": "hsl(var(--brand-lavender))",
        "brand-peach": "hsl(var(--brand-peach))",
        "brand-ochre": "hsl(var(--brand-ochre))",
        "brand-mint": "hsl(var(--brand-mint))",
        "brand-coral": "hsl(var(--brand-coral))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        radius: "var(--radius)",
      },
      borderRadius: {
        xs: "6px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        pill: "9999px",
        full: "9999px",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        section: "96px",
      },
      fontSize: {
        "display-xl": ["72px", { lineHeight: "1.0", letterSpacing: "-0.035em", fontWeight: "500" }],
        "display-lg": ["56px", { lineHeight: "1.05", letterSpacing: "-0.03em", fontWeight: "500" }],
        "display-md": ["40px", { lineHeight: "1.1", letterSpacing: "-0.025em", fontWeight: "500" }],
        "display-sm": ["32px", { lineHeight: "1.15", letterSpacing: "-0.015em", fontWeight: "500" }],
        "title-lg": ["24px", { lineHeight: "1.3", letterSpacing: "-0.012em", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "title-sm": ["16px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.55", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.55", fontWeight: "400" }],
        caption: ["13px", { lineHeight: "1.4", fontWeight: "500" }],
        "caption-uppercase": ["12px", { lineHeight: "1.4", letterSpacing: "0.12em", fontWeight: "600" }],
        button: ["14px", { lineHeight: "1.0", fontWeight: "600" }],
        "nav-link": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
